const fs = require('fs');

const newLevels = `
  {
    level: 53,
    cefr: "C1",
    title: "C1 — Advanced Verbs",
    emoji: "🔥",
    pairs: [
      { en: "mitigate", id: "meringankan" },
      { en: "exacerbate", id: "memperburuk" },
      { en: "alleviate", id: "meredakan" },
      { en: "corroborate", id: "membenarkan" },
      { en: "fluctuate", id: "berfluktuasi" },
      { en: "scrutinize", id: "meneliti" },
      { en: "vindicate", id: "membebaskan" },
      { en: "synthesize", id: "mensintesis" },
    ],
  },
  {
    level: 54,
    cefr: "C1",
    title: "C1 — Advanced Nouns",
    emoji: "🧠",
    pairs: [
      { en: "dichotomy", id: "dikotomi" },
      { en: "paradigm", id: "paradigma" },
      { en: "anomaly", id: "anomali" },
      { en: "ubiquity", id: "keberadaan di mana-mana" },
      { en: "epiphany", id: "pencerahan" },
      { en: "pragmatism", id: "pragmatisme" },
      { en: "synergy", id: "sinergi" },
      { en: "catalyst", id: "katalisator" },
    ],
  },
  {
    level: 55,
    cefr: "C1",
    title: "C1 — Advanced Adjectives",
    emoji: "✨",
    pairs: [
      { en: "ambiguous", id: "ambigu" },
      { en: "esoteric", id: "esoteris" },
      { en: "meticulous", id: "teliti" },
      { en: "profound", id: "mendalam" },
      { en: "resilient", id: "tangguh" },
      { en: "tangible", id: "nyata" },
      { en: "lucrative", id: "menguntungkan" },
      { en: "pervasive", id: "menyebar luas" },
    ],
  },
  {
    level: 56,
    cefr: "C1",
    title: "C1 — Academic Context",
    emoji: "🎓",
    pairs: [
      { en: "hypothesis", id: "hipotesis" },
      { en: "empirical", id: "empiris" },
      { en: "methodology", id: "metodologi" },
      { en: "variable", id: "variabel" },
      { en: "theoretical", id: "teoretis" },
      { en: "validate", id: "mengesahkan" },
      { en: "correlation", id: "korelasi" },
      { en: "discourse", id: "wacana" },
    ],
  },
  {
    level: 57,
    cefr: "TECH",
    title: "Tech — Cybersecurity",
    emoji: "🔐",
    pairs: [
      { en: "encryption", id: "enkripsi" },
      { en: "firewall", id: "tembok api" },
      { en: "malware", id: "perangkat perusak" },
      { en: "phishing", id: "pengelabuan" },
      { en: "breach", id: "pelanggaran" },
      { en: "authentication", id: "autentikasi" },
      { en: "vulnerability", id: "kerentanan" },
      { en: "hacker", id: "peretas" },
    ],
  },
  {
    level: 58,
    cefr: "TECH",
    title: "Tech — AI & Data",
    emoji: "🤖",
    pairs: [
      { en: "algorithm", id: "algoritma" },
      { en: "dataset", id: "kumpulan data" },
      { en: "neural network", id: "jaringan saraf" },
      { en: "machine learning", id: "pembelajaran mesin" },
      { en: "automation", id: "otomatisasi" },
      { en: "predictive", id: "prediktif" },
      { en: "bias", id: "bias" },
      { en: "model", id: "model" },
    ],
  },
  {
    level: 59,
    cefr: "TECH",
    title: "Tech — Web Dev",
    emoji: "🌐",
    pairs: [
      { en: "frontend", id: "ujung depan" },
      { en: "backend", id: "ujung belakang" },
      { en: "database", id: "basis data" },
      { en: "deployment", id: "penerapan" },
      { en: "server", id: "peladen" },
      { en: "framework", id: "kerangka kerja" },
      { en: "API", id: "API" },
      { en: "cache", id: "tembolok" },
    ],
  },
  {
    level: 60,
    cefr: "TECH",
    title: "Tech — Cloud & DevOps",
    emoji: "☁️",
    pairs: [
      { en: "container", id: "wadah" },
      { en: "scalability", id: "skalabilitas" },
      { en: "latency", id: "latensi" },
      { en: "microservices", id: "layanan mikro" },
      { en: "integration", id: "integrasi" },
      { en: "pipeline", id: "saluran pipa" },
      { en: "hosting", id: "penghostingan" },
      { en: "virtualization", id: "virtualisasi" },
    ],
  },
  {
    level: 61,
    cefr: "BUSINESS",
    title: "Business — Finance",
    emoji: "💰",
    pairs: [
      { en: "revenue", id: "pendapatan" },
      { en: "profit", id: "keuntungan" },
      { en: "investment", id: "investasi" },
      { en: "dividend", id: "dividen" },
      { en: "bankruptcy", id: "kebangkrutan" },
      { en: "asset", id: "aset" },
      { en: "liability", id: "kewajiban" },
      { en: "equity", id: "ekuitas" },
    ],
  },
  {
    level: 62,
    cefr: "BUSINESS",
    title: "Business — Marketing",
    emoji: "📈",
    pairs: [
      { en: "campaign", id: "kampanye" },
      { en: "branding", id: "pencitraan merek" },
      { en: "target audience", id: "target audiens" },
      { en: "conversion", id: "konversi" },
      { en: "engagement", id: "keterlibatan" },
      { en: "strategy", id: "strategi" },
      { en: "promotion", id: "promosi" },
      { en: "market share", id: "pangsa pasar" },
    ],
  },
  {
    level: 63,
    cefr: "BUSINESS",
    title: "Business — Startups",
    emoji: "🚀",
    pairs: [
      { en: "founder", id: "pendiri" },
      { en: "funding", id: "pendanaan" },
      { en: "pitch", id: "presentasi bisnis" },
      { en: "valuation", id: "valuasi" },
      { en: "venture capital", id: "modal ventura" },
      { en: "disruption", id: "gangguan" },
      { en: "pivot", id: "beralih arah" },
      { en: "incubator", id: "inkubator" },
    ],
  },
  {
    level: 64,
    cefr: "BUSINESS",
    title: "Business — HR",
    emoji: "👥",
    pairs: [
      { en: "recruitment", id: "perekrutan" },
      { en: "onboarding", id: "orientasi" },
      { en: "payroll", id: "penggajian" },
      { en: "appraisal", id: "penilaian" },
      { en: "turnover", id: "pergantian karyawan" },
      { en: "benefits", id: "tunjangan" },
      { en: "retention", id: "retensi" },
      { en: "compliance", id: "kepatuhan" },
    ],
  },
  {
    level: 65,
    cefr: "TRAVEL",
    title: "Travel — Airport",
    emoji: "✈️",
    pairs: [
      { en: "departure", id: "keberangkatan" },
      { en: "arrival", id: "kedatangan" },
      { en: "boarding pass", id: "pas naik" },
      { en: "customs", id: "bea cukai" },
      { en: "luggage", id: "bagasi" },
      { en: "gate", id: "gerbang" },
      { en: "delay", id: "penundaan" },
      { en: "passport", id: "paspor" },
    ],
  },
  {
    level: 66,
    cefr: "TRAVEL",
    title: "Travel — Hotel",
    emoji: "🏨",
    pairs: [
      { en: "reservation", id: "reservasi" },
      { en: "reception", id: "resepsionis" },
      { en: "check-in", id: "lapor masuk" },
      { en: "check-out", id: "lapor keluar" },
      { en: "suite", id: "kamar suite" },
      { en: "amenities", id: "fasilitas" },
      { en: "concierge", id: "pramu tamu" },
      { en: "lobby", id: "lobi" },
    ],
  },
  {
    level: 67,
    cefr: "TRAVEL",
    title: "Travel — Tourism",
    emoji: "🗺️",
    pairs: [
      { en: "itinerary", id: "rencana perjalanan" },
      { en: "souvenir", id: "cendera mata" },
      { en: "guide", id: "pemandu" },
      { en: "landmark", id: "tengara" },
      { en: "excursion", id: "darmawisata" },
      { en: "sightseeing", id: "tamasya" },
      { en: "monument", id: "monumen" },
      { en: "destination", id: "tujuan" },
    ],
  },
  {
    level: 68,
    cefr: "TRAVEL",
    title: "Travel — Transportation",
    emoji: "🚆",
    pairs: [
      { en: "subway", id: "kereta bawah tanah" },
      { en: "platform", id: "peron" },
      { en: "ticket", id: "tiket" },
      { en: "ferry", id: "feri" },
      { en: "schedule", id: "jadwal" },
      { en: "commute", id: "perjalanan harian" },
      { en: "transit", id: "persinggahan" },
      { en: "shuttle", id: "kendaraan antar-jemput" },
    ],
  },
  {
    level: 69,
    cefr: "B1",
    title: "B1 — Medical & Health",
    emoji: "🩺",
    pairs: [
      { en: "symptom", id: "gejala" },
      { en: "disease", id: "penyakit" },
      { en: "treatment", id: "perawatan" },
      { en: "prescription", id: "resep obat" },
      { en: "pharmacy", id: "apotek" },
      { en: "surgery", id: "operasi" },
      { en: "vaccine", id: "vaksin" },
      { en: "recovery", id: "pemulihan" },
    ],
  },
  {
    level: 70,
    cefr: "B1",
    title: "B1 — Environment",
    emoji: "🌍",
    pairs: [
      { en: "pollution", id: "polusi" },
      { en: "climate", id: "iklim" },
      { en: "conservation", id: "pelestarian" },
      { en: "ecosystem", id: "ekosistem" },
      { en: "recycling", id: "daur ulang" },
      { en: "renewable", id: "terbarukan" },
      { en: "habitat", id: "habitat" },
      { en: "emissions", id: "emisi" },
    ],
  },
  {
    level: 71,
    cefr: "B2",
    title: "B2 — Culinary & Food",
    emoji: "🍳",
    pairs: [
      { en: "ingredients", id: "bahan-bahan" },
      { en: "recipe", id: "resep" },
      { en: "cuisine", id: "masakan" },
      { en: "appetizer", id: "makanan pembuka" },
      { en: "beverage", id: "minuman" },
      { en: "gourmet", id: "makanan lezat" },
      { en: "seasoning", id: "bumbu" },
      { en: "nutrition", id: "gizi" },
    ],
  },
  {
    level: 72,
    cefr: "B2",
    title: "B2 — Education",
    emoji: "🏫",
    pairs: [
      { en: "curriculum", id: "kurikulum" },
      { en: "scholarship", id: "beasiswa" },
      { en: "tuition", id: "uang sekolah" },
      { en: "graduation", id: "kelulusan" },
      { en: "faculty", id: "fakultas" },
      { en: "semester", id: "semester" },
      { en: "assignment", id: "tugas" },
      { en: "lecture", id: "kuliah" },
    ],
  },
  {
    level: 73,
    cefr: "C1",
    title: "C1 — Politics & Law",
    emoji: "⚖️",
    pairs: [
      { en: "legislation", id: "perundang-undangan" },
      { en: "jurisdiction", id: "yurisdiksi" },
      { en: "amendment", id: "amandemen" },
      { en: "constitution", id: "konstitusi" },
      { en: "democracy", id: "demokrasi" },
      { en: "diplomacy", id: "diplomasi" },
      { en: "treaty", id: "perjanjian" },
      { en: "sovereignty", id: "kedaulatan" },
    ],
  },
  {
    level: 74,
    cefr: "C1",
    title: "C1 — Philosophy",
    emoji: "🤔",
    pairs: [
      { en: "existential", id: "eksistensial" },
      { en: "ethics", id: "etika" },
      { en: "metaphysics", id: "metafisika" },
      { en: "epistemology", id: "epistemologi" },
      { en: "morality", id: "moralitas" },
      { en: "nihilism", id: "nihilisme" },
      { en: "determinism", id: "determinisme" },
      { en: "consciousness", id: "kesadaran" },
    ],
  },
  {
    level: 75,
    cefr: "C1",
    title: "C1 — Arts & Literature",
    emoji: "🎭",
    pairs: [
      { en: "aesthetics", id: "estetika" },
      { en: "metaphor", id: "metafora" },
      { en: "protagonist", id: "protagonis" },
      { en: "narrative", id: "narasi" },
      { en: "satire", id: "satir" },
      { en: "genre", id: "genre" },
      { en: "critique", id: "kritik" },
      { en: "masterpiece", id: "karya agung" },
    ],
  },
  {
    level: 76,
    cefr: "SLANG",
    title: "Slang — Gen Z Lingo",
    emoji: "🧢",
    pairs: [
      { en: "no cap", id: "jujur (tanpa bohong)" },
      { en: "ghosting", id: "menghilang tanpa kabar" },
      { en: "flex", id: "pamer" },
      { en: "salty", id: "kesal / marah" },
      { en: "shook", id: "terkejut" },
      { en: "tea", id: "gosip" },
      { en: "sus", id: "mencurigakan" },
      { en: "lit", id: "keren / seru" },
    ],
  },
  {
    level: 77,
    cefr: "SLANG",
    title: "Slang — Pop Culture",
    emoji: "🎬",
    pairs: [
      { en: "stan", id: "penggemar fanatik" },
      { en: "bop", id: "lagu enak" },
      { en: "flop", id: "gagal total" },
      { en: "vibe", id: "suasana" },
      { en: "iconic", id: "ikonik" },
      { en: "savage", id: "ganas / keren" },
      { en: "mood", id: "suasana hati (relatable)" },
      { en: "lowkey", id: "diam-diam" },
    ],
  },
  {
    level: 78,
    cefr: "BUSINESS",
    title: "Business — Entrepreneur",
    emoji: "💼",
    pairs: [
      { en: "networking", id: "membangun relasi" },
      { en: "freelance", id: "pekerja lepas" },
      { en: "outsource", id: "alih daya" },
      { en: "prototype", id: "purwarupa" },
      { en: "margin", id: "margin" },
      { en: "niche", id: "ceruk pasar" },
      { en: "merger", id: "penggabungan" },
      { en: "acquisition", id: "akuisisi" },
    ],
  },
  {
    level: 79,
    cefr: "TECH",
    title: "Tech — Crypto & Web3",
    emoji: "🪙",
    pairs: [
      { en: "blockchain", id: "rantai blok" },
      { en: "cryptocurrency", id: "mata uang kripto" },
      { en: "decentralized", id: "terdesentralisasi" },
      { en: "token", id: "token" },
      { en: "wallet", id: "dompet (digital)" },
      { en: "mining", id: "penambangan" },
      { en: "smart contract", id: "kontrak pintar" },
      { en: "ledger", id: "buku besar" },
    ],
  },
  {
    level: 80,
    cefr: "C1",
    title: "C1 — Ultimate Challenge",
    emoji: "🏆",
    pairs: [
      { en: "quintessential", id: "paling sempurna" },
      { en: "serendipity", id: "kebetulan yang menyenangkan" },
      { en: "cacophony", id: "suara sumbang" },
      { en: "ephemeral", id: "fana" },
      { en: "ineffable", id: "tak terlukiskan" },
      { en: "obfuscate", id: "membingungkan" },
      { en: "paradox", id: "paradoks" },
      { en: "sycophant", id: "penjilat" },
    ],
  }
`;

const targetFile = 'c:/Users/CECE ADITYA/.gemini/antigravity-ide/scratch/mr-cece/data/vocabulary.ts';
let content = fs.readFileSync(targetFile, 'utf-8');

// replace the last '];' with our new levels + '];'
if (content.endsWith('];\n') || content.endsWith('];\r\n') || content.trim().endsWith('];')) {
  const lastIndex = content.lastIndexOf('];');
  content = content.substring(0, lastIndex) + newLevels + '\\n];\\n';
  fs.writeFileSync(targetFile, content);
  console.log("Successfully expanded vocabulary to 80 levels!");
} else {
  console.log("Error: could not find closing bracket.");
}
